### ISSUE TITLE
Not working in Linux for 1.0.0-beta7 coreclr x64

### ISSUE THREAD

**Issue by zhangxin511** [aspnet/HttpClient#29]
I am new to ASP.NET vnext, probably something is wrong of my own configuration. When I used the sample in this repository, I am not able to have it working properly.

So my environment is below, I am using 1.0.0-beta7 coreclr x64 on Ubuntu desktop 14.04 (VM running on virtulbox):
Active Version              Runtime Architecture OperatingSystem Alias
------    -------                  -------     ------------        ---------------           -----
  *       1.0.0-beta7        coreclr   x64               linux                  default
       1.0.0-beta7          mono                 linux/osx       
       1.0.0-beta8-15613    coreclr x64          linux           
       1.0.0-beta8-15613    mono                 linux/osx   

I first restored dependency:
xzhang@xzhang-VirtualBox:~/Downloads/HttpClient-dev/samples/TestClient$ dnu restore
Then I run "dnx run" at the same folder, I got output:
xzhang@xzhang-VirtualBox:~/Downloads/HttpClient-dev/samples/TestClient$ dnx run
System.ArgumentException: The AddressFamily 117 is not valid for the System.Net.IPEndPoint end point, use InterNetwork instead.
Parameter name: socketAddress
   at System.Net.IPEndPoint.Create(SocketAddress socketAddress)
   at System.Net.Dns.TryGetAddrInfo(String name, AddressInfoHints flags, IPHostEntry& hostinfo)
   at System.Net.Dns.TryGetAddrInfo(String name, IPHostEntry& hostinfo)
   at System.Net.Dns.GetAddrInfo(String name)
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.TcpClient.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Sockets.TcpClient.ConnectAsync(String host, Int32 port)
   at Microsoft.Net.Http.Client.ManagedHandler.<ConnectAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Net.Http.Client.ManagedHandler.<ProcessRequestAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Net.Http.Client.ManagedHandler.<SendAsync>d__13.MoveNext()

I tried to use some other addresses and each time I get some other The AddressFamily errors codes.

**Comment by zhangxin511** [comment]
I also modified the code as below, with same project.json from the sample, I got different errors. Not sure if it is because code issue or library problem:

using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.Net.Http.Client;

namespace ProductStoreClient
{
    class Program
    {
        static void Main()
        {
            RunAsync().Wait();
        }

        static async Task RunAsync()
        {
            using (var client = new HttpClient())
		{
		    var baseUri = "http://playapi.azurewebsites.net/api/products";
		    client.BaseAddress = new Uri(baseUri);
		    client.DefaultRequestHeaders.Accept.Clear();
		    var response = await client.GetAsync(baseUri);
		    if (response.IsSuccessStatusCode)
		    {
			var responseJson = await response.Content.ReadAsStringAsync();
			Console.WriteLine(responseJson);
		    }else{
			Console.WriteLine();	
			}
		}
        }
    }
}


The error I got is:
xzhang@xzhang-VirtualBox:~/Downloads/HttpClient-dev/samples/TestClient$ dnx run
System.DllNotFoundException: Unable to load DLL 'winhttp.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.WinHttp.WinHttpOpen(IntPtr userAgent, UInt32 accessType, String proxyName, String proxyBypass, Int32 flags)
   at System.Net.Http.WinHttpHandler.EnsureSessionHandleExists(RequestState state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__120.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ProductStoreClient.Program.<RunAsync>d__1.MoveNext()

**Comment by zhangxin511** [comment]
I do have both these two program working fine on win7 64bit using coreclr 1.0.0-beta7. This issue only happens on Linux.

**Comment by Tratcher** [comment]
This repo is obsolete and will be removed soon. The normal System.Net.Http.HttpClient now supports Linux/Mac but there's still some work to get nuget packages that contain the linux/mac binaries.

**Comment by zhangxin511** [comment]
Thank you for your super fast (I really mean it!) response!
Actually I started from System.Net.Http.HttpClient, and I kept on getting the "Unable to load DLL 'winhttp.dll'“ on Linux. Then I search online and find this library and try to test my luck.

Could you give me more details about how to get nuget packages that contains the linux/max binaries? 
I only added below feed to my nuget config in Linux:
    https://www.myget.org/F/aspnetvnext/api/v2/
    https://www.nuget.org/api/v2/

Do I need to something else to make the magic happens? I have searched and tried 2 days online and didn't find quite useful information.

Thank you!

**Comment by Tratcher** [comment]
The packages aren't available yet. We directly deploy the binary with dnx. Let's take this discussion to https://github.com/aspnet/dnx/issues/2703
